
USE trailersdb;

INSERT INTO trailer (id_trailer, nombre_trailer, url_cover_trailer, vistas) 
    VALUES 
        ('D09aGdEDK2U', 
            'TERMINATOR 7: End Of War (2022) Official Trailer Teaser - Arnold Schwarzenegger',
            'https://img.youtube.com/vi/D09aGdEDK2U/hqdefault.jpg',
            15),
        ('jaAiz_-ZLvI', 
            'CREED 3 Tráiler Español (2023)',
            'https://img.youtube.com/vi/jaAiz_-ZLvI/hqdefault.jpg',
            15),
        ('fbZyLF16pgE', 
            'ONE PIECE FILM RED Último Tráiler Español Latino (Nuevo, 2022)',
            'https://img.youtube.com/vi/fbZyLF16pgE/hqdefault.jpg',
            15),
        ('XvqWZOPJN0Y', 
            'SIN NOVEDAD EN EL FRENTE Tráiler Español Latino Subtitulado (2022)',
            'https://img.youtube.com/vi/XvqWZOPJN0Y/hqdefault.jpg',
            15),
        ('4QJOLNASevs', 
            'EL PEOR VECINO DEL MUNDO Tráiler Español (2022) Tom Hanks',
            'https://img.youtube.com/vi/4QJOLNASevs/hqdefault.jpg',
            15),
        ('yerGXcQEXUo', 
            'L\'IMMENSITÁ Tráiler Español (2022) Penélope Cruz',
            'https://img.youtube.com/vi/yerGXcQEXUo/hqdefault.jpg',
            15),
        ('UajwHWUXY7k', 
            'BLACK ADAM \"Hay Héroes y Hay Villanos\" Tráiler Español Latino Subtitulado (2022)',
            'https://img.youtube.com/vi/UajwHWUXY7k/hqdefault.jpg',
            15),
        ('jNj2QUD_jCI', 
            'POKER FACE Tráiler (2022)',
            'https://img.youtube.com/vi/jNj2QUD_jCI/hqdefault.jpg',
            15),
        ('bjki2_w8Rtk', 
            'SPIRITED Tráiler (2022) Ryan Reynolds, Will Ferrell',
            'https://img.youtube.com/vi/bjki2_w8Rtk/hqdefault.jpg',
            15),
        ('lMVtVRffw9o', 
            'YO ME ENCARGO DE LA CERVEZA Tráiler Español (2022) Zac Efron',
            'https://img.youtube.com/vi/lMVtVRffw9o/hqdefault.jpg',
            15),
        ('AYoLBi0tL_0', 
            'NOCHE SIN PAZ Tráiler Español Latino Subtitulado (2022)',
            'https://img.youtube.com/vi/AYoLBi0tL_0/hqdefault.jpg',
            15),
        ('4NrgOIDHNGg', 
            'UNA BODA EXPLOSIVA Tráiler Español (2022) Jennifer Lopez',
            'https://img.youtube.com/vi/4NrgOIDHNGg/hqdefault.jpg',
            15);

DROP TABLE trailer;